export const SAVE_CALCULATION = 'SAVE_CALCULATION';
export const DELETE_CALCULATION = 'DELETE_CALCULATION';
export const CHANGE_CALCULATION_NAME = 'CHANGE_CALCULATION_NAME';
export const CALCULATE_PRICE = 'CALCULATE_PRICE';
export const FILTER_CALCULATIONS = 'FILTER_CALCULATIONS';
